services:
  backend:
    build:
      context: fastapi_backend
    environment:
      OPENAPI_OUTPUT_FILE: ./shared-data/openapi.json
      DATABASE_URL: sqlite+aiosqlite:///./shared-data/app.db
      TEST_DATABASE_URL: sqlite+aiosqlite:///./shared-data/test.db
      MAIL_SERVER: mailhog
      FRONTEND_URL: http://localhost:3000
      CORS_ORIGINS: '["*"]'
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes:
      - fastapi-venv:/app/.venv
      - ./local-shared-data:/app/shared-data

  frontend:
    build:
      context: ./nextjs-frontend
    user: node
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      NODE_ENV: development
      API_BASE_URL: http://backend:8000
      OPENAPI_OUTPUT_FILE: ./shared-data/openapi.json
    volumes:
      - ./nextjs-frontend:/app
      - nextjs-node-modules:/app/node_modules
      - ./local-shared-data:/app/shared-data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - my_network

volumes:
  nextjs-node-modules:
  fastapi-venv:

networks:
  my_network:
    driver: bridge
